# baseURL = 'http://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'
# theme = 'ananke'
baseURL = 'https://windbelike.vercel.app/'
languageCode = 'en-us'
title = 'new site ...'
theme = 'paper'
